config/routes.rb
Rails.application.routes.draw do

  get 'main/list'
  root 'home#index'
  get 'home/index'

  resources :users
  resources :recipes
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new',        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'list',   to: 'main#list',        as: 'list'
  get 'new',    to: 'main#new',         as: 'new'
  get 'edit',   to: 'main#edit',        as: 'editform'


  post 'destroy', to: 'recipes#destroy'
  post  'change',  to: 'recipes#change'
  post 'edit',   to: 'main#edit',        as: 'editaction'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def current_user
        if session[:user_id]
        @current_user ||= User.find(session[:user_id])
        else
        @current_user = nil
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :setrecipies

  def list
  end

  def edit

    recipe = Recipe.where(title: params[:old_name])
    if params[:receipt] != NIL
      i = 0
        params[:receipt].each do |db|
          asd1 = db.map { |i| "#{i}" }.last
          if asd1 == NIL
          else
            if i == 0
              recipe.update(title: asd1)
              break
            end
          end
          i = i + 1
        end

      i = 0
        params[:receipt].each do |db|
          asd2 = db.map { |i| "#{i}" }.last
          if asd2 == NIL
          else
            if i == 1
              recipe.update(description: asd2)
              break
            end
          end
          i = i + 1
        end

      i = 0
      tomb = []
        params[:receipt].each do |db|
          asd3 = db.map { |i| "#{i}" }.last
          if asd3 == NIL
          else
            if i == 2
              tomb.push(Tag.new(name: asd3))
              break
            end
          end
          i = i + 1
        end
      recipe.update(tags: tomb)

    end
  end

  private
  def setrecipies
    @recipes = Recipe.where(user:current_user)

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def create
    recipe = Recipe.new
    if params[:receipt]["title"] == ""
        flash.now[:alert] = "Cannot create a receipt without title"

    elsif params[:receipt]["text"] == ""

      flash.now[:alert] = "Cannot create a receipt without description"

    else
      recipe.title = params[:receipt]["title"]
      recipe.description = params[:receipt]["text"]
      recipe.user = current_user
      temp = params[:receipt]["tags"].split(",")
      tomb = []
      temp.each do |recipee|
        recipee = recipee.gsub(/\s+/, "")
        tomb.push(Tag.new(name: recipee))
      end
      recipe.tags = tomb
      recipe.save!
      redirect_to "/main/list"

    end
  end

  def change
    session[:chosen] = params[:chose]
  end

  def destroy
    Recipe.where(["title = ?",params[:name]]).destroy_all
      redirect_to "/main/list"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to main_list_url
    else
      flash.now[:alert] = "Email or password is invalid"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container" style="text-align: center">

  <h1>Welcome on the Webpage</h1>
  <p>Here you can create new recipes</p>

  <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
    <% end %>

  <%= form_tag sessions_path do |form| %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>  <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>  <div class="actions">
    <%= submit_tag "Login" %>
    
  </div>
  <% end %>
  <%= link_to "Sign Up", signup_path %>
  <p id="alert"><%= alert %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/edit.html.erb
<div class="container" style="text-align: center">
  <h1>Edit recept</h1>
  <%= form_with scope: :receipt, url: "/edit", local: true do |form| %>
    <p>
      <input type="hidden" value="<%= session[:chosen] %>" name="old_name">
      <%= form.label :title %>
      <%= form.text_area :title %>
    </p>

    <p>
      <%= form.label :Description %>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.label :Tags %>
      <%= form.text_area :tags, placeholder: "Tag1, Tag2, Tag3" %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'Back', list_path %>
</div>

<script type="text/javascript">

    let titles = []
    let descs  = []
    let tags   = []
    let i      = 0

    <% @recipes.each do |recipe| %>

    titles[i] = "<%= recipe.title %>"
    descs[i]  = "<%= recipe.description %>"
    tags[i]   = "<%= (recipe.tags.map{ |t| t.name }).join(", ") %>"
    i = i + 1;

    <% end %>
    for( let j = 0; j < i; j++ ) {
        if (titles[j] == '<%= session[:chosen] %>') {
            document.getElementById("receipt_title").innerHTML = titles[j]
            document.getElementById("receipt_text").innerHTML = descs[j]
            document.getElementById("receipt_tags").innerHTML = tags[j]
        }
    }

</script>

app/views/main/list.html.erb
<div class="container">
  <div class="navbar navbar-dark bg-dark rounded" style="color: white; margin-top: -35px;">
    <div class="col-1">
      <h1>Cooks</h1>
    </div>
    <div class="col-1 btn btn-outline-secondary btn-sm">
      Recipes
    </div>
    <div class="col-8" style="text-align: right">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path %>
      <% end %>
    </div>
  </div>

  <div class="row" style="height: 50px;"></div>

  <div class="container">
    <div class="row p-0 ">
      <div class="col-2" style="width: 30%">
        <% @recipes.each do |recipe| %>
          <div class="row">
            <div class="col p-0 m-0">
              <%= button_to recipe.title, {:controller => "recipes", :action => "change"}, {:method => :post, :onclick => "Call('#{recipe.title}')", class: 'btn btn-dark w-100', :params => { chose: recipe.title }}  %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-10" style="background-color: lightgray">
          <div class="row">
            <div class="col">
             <p class="row-1" id="desc"></p>
            </div>
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2"></div>
      <div class="col-7" id="tag" style="background-color: lightgray">

      </div>
      <div class="col-3 text-right" id="buttons" style="background-color: lightgray">
        <button onclick="location.href='/new'">New</button>
        <button onclick="Call2()">Edit</button>
        <%= button_to 'Delete', {:controller => "recipes", :action => "destroy"}, :method => :post, :params => { name: session[:chosen] } %>
      </div>
    </div>

  </div>


  <script type="text/javascript">

      function Call2(){
          if ( '<%= session[:chosen] %>' == " " ){
              alert("Select a receipt")
          }else{
              location.href='/edit'
          }
      }

      function Call(arg1){
          let titles = []
          let descs  = []
          let tags   = []
          let i      = 0

          <% @recipes.each do |recipe| %>

                titles[i] = "<%= recipe.title %>"
                descs[i]  = "<%= recipe.description %>"
                tags[i]   = "<%= (recipe.tags.map{ |t| t.name }).join(", ") %>"
                i = i + 1;

          <% end %>
          for( let j = 0; j < i; j++ ) {
              if( titles[j] == arg1 ) {
                  document.getElementById("desc").innerHTML = descs[j]
                  document.getElementById("tag").innerHTML = tags[j]
              }
          }
      }

  </script>

  <div class="footer">
  </div>
</div>

app/views/main/new.html.erb
<div class="container" style="text-align: center">
  <%= form_with scope: :receipt, url: recipes_path, local: true do |form| %>
    <p>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.label :Tags %>
      <%= form.text_area :tags, placeholder: "Tag1, Tag2, Tag3" %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'Back', list_path %>
</div>

app/views/users/_form.html.erb
<div class="container" style="text-align: center">
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container" style="text-align: center">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container" style="text-align: center">
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container" style="text-align: center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>